class Config():

    # Timings
    HEARTBEAT_INTERVAL = 0.5
    SCHEDULING_RESOLUTION = 0.5
    FIRE_DURATION = 0.1
    PROGRAM_RESOLUTION = 0.05
    STATUS_STREAM_INTERVAL = 0.5
    TESTLOOP_INTERVAL = 0.5
